version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: week12-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: week12-admin
      MONGO_INITDB_ROOT_PASSWORD: week12-pass
      MONGO_INITDB_DATABASE: week12
    volumes:
      - ./data/db:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js